name: Code Checker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  get-files-changed:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.changed-files-specific.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get all changed *.py file(s)
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.py
          
  linter:
    runs-on: ubuntu-latest
    needs: get-files-changed
    env:
      FILES: ${{needs.get-files-changed.outputs.files}}
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --diff"
          src: "$FILES"
  formatter:
    runs-on: ubuntu-latest
    needs: get-files-changed
    env:
      FILES: ${{needs.get-files-changed.outputs.files}}
    steps:
      - uses: actions/checkout@v3
      - name: Install flake8 and its plugins
        run: pip install flake8 flake8-docstrings
      - name: Run flake8
        run: |
          flake8 $FILES --max-line-length=100 --ignore=H102,H103,W503,H238,E203
  isort:
    runs-on: ubuntu-latest
    needs: get-files-changed
    env:
      FILES: ${{needs.get-files-changed.outputs.files}}
    steps:
      - uses: actions/checkout@v3
      - uses: isort/isort-action@v1
        with:
          sort-paths: "$FILES"
