name: Code Checker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  get-files-changed:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "files<<EOF" >> ${GITHUB_ENV}
          echo "$(gh pr diff --name-only --repo ${{ github.repository }} ${{ github.event.pull_request.number }} | grep .py$ | sed 's/^/.\//' | tr '\n' ' ')" >> ${GITHUB_ENV}
          echo "EOF" >> ${GITHUB_ENV}
          echo "${{ env.files }}"
          echo ${{ github.event.pull_request.changed_files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get all changed *.py file(s)
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.py
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          echo "${{ steps.changed-files-specific.outputs.all_changed_files }}"
    
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --diff"
          src: "${{ env.files }}"
  formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install flake8 and its plugins
        run: pip install flake8 flake8-docstrings
      - name: Run flake8
        run: |
          flake8 ${{ env.files }} --max-line-length=100 --ignore=H102,H103,W503,H238,E203
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isort/isort-action@v1
        with:
          sort-paths: "${{ env.files }}"
