name: Final Message

on:
  pull_request:
    branches:
      - master
    types:
      - closed
    paths:
      - 'ex[1-9]/**'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            @${{ github.event.pull_request.user.login }}
            以上でこの課題は終了です．お疲れ様でした！
